### ISSUE TITLE
OpenMS v2.0.0 - Dependencies required

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/packager-base#132]
OpenMS v2.0.0 currently needs `qtwebkit-devel` and `libsvm-devel` to be able to compile. These are currently only available in EPEL, spoke with @mjtko and decided these will need to be brought in as requirements.

**Comment by mjtko** [comment]
I think `qtwebkit-devel` should be available as part of `libs/qt`. We’ll still need `libsvm` though.

**Comment by mjtko** [comment]
While some work has been done on this, it’s still stalled as the python variant isn’t yet building correctly.

**Comment by mjtko** [comment]
Python variant fixed in 670ca6239dc75c852895abb218c0c00552b86eb8.
