### ISSUE TITLE
rmblast v2.2.7 - too large for device

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/packager-base#148]
`Installation complete.
Error response from daemon: Untar re-exec error: exit status 1: output: write /var/cache/gridware/src/apps/rmblast/2.2.27/gcc-4.8.5/rmblast-2.2.27-src/c++/GCC485-DebugMT64/bin/tblastx: no space left on device`

Is this a setting we can change, or does it need doing locally and then uploading?

**Comment by mjtko** [comment]
Looks to me like we'll need to build this one on EC2, `export` and upload.

**Comment by mjtko** [comment]
Closed via #146 and https://github.com/alces-software/gridware-ci/commit/322ea1e60f10f25a8841274265df7e69bd46bf12
