### ISSUE TITLE
libs/nvidia-cuda auto driver install

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/packager-base#184]
Ephemeral GPU nodes don't have a driver installed by default, we need to add a script that would detect a GPU card, (grep -i nvidia)? and run the driver installer non-interactively if there is no nvidia driver loaded (modprobe nvidia fails). There may be some clues in the symphony puppet init script on how to do this.. https://raw.githubusercontent.com/ste78/puppet-alcesbase/master/files/gpu/alces-nvidia.init

**Comment by mjtko** [comment]
We have the beginnings of this here:

https://github.com/alces-software/clusterware-handlers/tree/master/nvidia-driver

It doesn't do any detection currently and requires `libs/nvidia-cuda` to be installed, but should act as a starting point.

**Comment by mjtko** [comment]
Thoughts on how to rework this:

Enabling the handler should not require `libs/nvidia-cuda`. Instead, at `initialize` time, the handler should detect the presence of one or more NVIDIA cards (using heuristic as here: https://github.com/alces-software/clusterware-handlers/blob/master/nvidia-driver/initialize#L67).  If presence is detected and `modprobe` fails, install a depot (say, `nvidia-driver`) and proceed with driver installation and device creation.

We could then have the handler enabled in all Flight Compute images.

**Comment by sierra-tango-echo** [comment]
further testing of this after I logged the bug showed that we'd potentially need different drivers for different instance types, so some sort of card instance detection then loading a known working driver for that instance might also be needed 😐

**Comment by wdm78** [comment]
If it helps - tested version 361.42 (http://uk.download.nvidia.com/XFree86/Linux-x86_64/361.42/NVIDIA-Linux-x86_64-361.42.run) on a g2.2xlarge instance, and that worked OK.

**Comment by mjtko** [comment]
At the moment we use the driver bundled with the CUDA release.  Is it looking like we'll need a different mechanism to fetch/install drivers for specific machine types?

**Comment by sierra-tango-echo** [comment]
i'd say we need to test drivers against instance, each time we roll a new cuda cuz the driver is both linked to the cuda version and the hardware type. we'd need a mechanism to install the one we've said works with a particular instance

**Comment by mjtko** [comment]
Ok - sounds like a use case for multiple depots.  How about:
1. perform GPU detection
   1. If on AWS use machine type to determine whether we need GPU support
   2. Otherwise: something else TBC
2. if modinfo/modprobe fails then the image doesn't yet provide support and we need some. If it doesn't fail, we're done already.
3. grab and install `gpu-support-<detected value>` depot
4. load `gpu-support-<detected value>/libs/nvidia-cuda` module and install driver
5. create devices

**Comment by mjtko** [comment]
This issue was moved to alces-software/clusterware-handlers#33
