### ISSUE TITLE
Typo in bioconductor group

### ISSUE THREAD

**Issue by benarmston** [alces-software/packager-base#395]
There is a typo in all of the metadata files for bioconductor.  Bioinformatics has been spelled as Bioninformatics (the first 'n' should not be there).

https://github.com/alces-software/packager-base/blob/master/libs/bioconductor/3.3/metadata.yml#L31

**Comment by mjtko** [comment]
PRs welcomed :)

**Comment by RuanEllis** [comment]
Fixed as part of https://github.com/alces-software/packager-base/commit/2d0cdf1be13a18ccfb321332024f2bf74b071446
