### ISSUE TITLE
ABySS v1.5.2 - No smoke tests

### ISSUE THREAD

**Issue by andrewprovis** [alces-software/packager-base#403]
Need to create standard method for performing smoke test with `alces template` PR #397

@RuanEllis - Can you take a look at this please.

**Comment by mjtko** [comment]
What's this getting at? Can we not have the smoke test and the example script? Or is there another intention here?

**Comment by andrewprovis** [comment]
Smoke test has been generated for ABySS. Now using example scripts as smoke tests.
