### ISSUE TITLE
Create: OpenDroneMap

### ISSUE THREAD

**Issue by wdm78** [alces-software/packager-base#474]
Please create a package to install OpenDroneMap - http://opendronemap.github.io/odm

**Comment by andrewprovis** [comment]
I'll take a shot at this :)

**Comment by andrewprovis** [comment]
Work in progress in this branch: https://github.com/alces-software/packager-base/tree/create/opendronemap-0.2

**Comment by mjtko** [comment]
This was achieved using a Docker build instead.
