### ISSUE TITLE
Multiz/TBA won't compile on EL7

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/packager-base#88]
Currently won't compile on base EL7 image - fine on an EL6 image. Current error is:
`maf_project.c: In function ‘main’:
maf_project.c:573:41: error: variable ‘x’ set but not used [-Werror=unused-but-set-variable]
     char cmd[500], *target, **species, *x;
                                         ^
maf_project.c:570:30: error: variable ‘location’ set but not used [-Werror=unused-but-set-variable]
     struct mafComp *c, *b, **location;
                              ^
cc1: all warnings being treated as errors
make: *** [maf_project] Error 1`

**Comment by mjtko** [comment]
Closed via #252
